// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// No code samples exist for BillingRequestWithActions in the schema.

describe.skip('BillingRequestWithActions Code Samples', () => {
   
  test.skip('no code samples in schema', () => {});
});
