// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

import * as nock from 'nock';
import { GoCardlessClient } from '../client';
import { Environments } from '../constants';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as Types from '../types/Types';

describe('Creditors Code Samples', () => {
  const token = 'SECRET_TOKEN';
  let client: GoCardlessClient;

  beforeAll(() => {
    nock.disableNetConnect();
  });

  beforeEach(() => {
    client = new GoCardlessClient(token, Environments.Live, {});
  });

  afterEach(() => {
    nock.cleanAll();
  });

  test('create code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/creditors';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { creditors: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const creditor = await client.creditors.create({
        name: 'Acme',
        country_code: 'GB',
        creditor_type: 'company',
        bank_reference_prefix: 'ACME',
      });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('list code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/creditors';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { creditors: [{}], meta: { cursors: {}, limit: 50 } };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const creditors = await client.creditors.list();

      // List the first three creditors.
      const limitedCreditors = await client.creditors.list({ limit: '3' });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('get code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/creditors/:identity';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { creditors: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const creditor = await client.creditors.find('CR123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('update code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/creditors/:identity';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { creditors: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').put(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const creditor = await client.creditors.update('CR123', {
        links: {
          default_gbp_payout_account: 'BA789',
        },
      });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });
});
