// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

import * as nock from 'nock';
import { GoCardlessClient } from '../client';
import { Environments } from '../constants';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as Types from '../types/Types';

describe('InstalmentSchedules Code Samples', () => {
  const token = 'SECRET_TOKEN';
  let client: GoCardlessClient;

  beforeAll(() => {
    nock.disableNetConnect();
  });

  beforeEach(() => {
    client = new GoCardlessClient(token, Environments.Live, {});
  });

  afterEach(() => {
    nock.cleanAll();
  });

  test('create_with_dates code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/instalment_schedules';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { instalment_schedules: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const instalmentSchedule = await client.instalmentSchedules.createWithDates(
        {
          name: 'ACME Invoice 103',
          total_amount: '10000', // 100 GBP in pence
          app_fee: '10', // Your 10 pence fee per instalment
          currency: 'GBP',
          instalments: [
            {
              charge_date: '2019-08-20',
              amount: '3400',
            },
            {
              charge_date: '2019-09-03',
              amount: '3400',
            },
            {
              charge_date: '2019-09-17',
              amount: '3200',
            },
          ],
          links: {
            mandate: 'MD0000XH9A3T4C',
          },
          metadata: {},
        },
        'instalment_schedule_idempotency_key',
      );
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('create_with_schedule code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/instalment_schedules';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { instalment_schedules: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const instalmentSchedule = await client.instalmentSchedules.createWithSchedule(
        {
          name: 'ACME Invoice 103',
          total_amount: '10000', // 100 GBP in pence, collected from the customer
          app_fee: '10', // Your 10 pence fee, applied to each instalment,
          // to be paid out to you
          currency: 'GBP',
          instalments: {
            start_date: '2019-08-20',
            interval_unit: 'weekly',
            interval: 2,
            amounts: ['3400', '3400', '3200'],
          },
          links: {
            mandate: 'MD0000XH9A3T4C',
          },
          metadata: {},
        },
        'instalment_schedule_idempotency_key',
      );
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('list code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/instalment_schedules';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { instalment_schedules: [{}], meta: { cursors: {}, limit: 50 } };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const instalmentSchedules = await client.instalmentSchedules.list();

      // List all instalment schedules associated with a given customer.
      const customerInstalmentSchedules = await client.instalmentSchedules.list({ customer: 'CU123' });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('get code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/instalment_schedules/:identity';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { instalment_schedules: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const instalmentSchedule = await client.instalmentSchedules.find('IS123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('update code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/instalment_schedules/:identity';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { instalment_schedules: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').put(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const instalmentSchedule = await client.instalmentSchedules.update('IS123', {
        metadata: {
          key: 'value',
        },
      });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('cancel code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/instalment_schedules/:identity/actions/cancel';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { instalment_schedules: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const instalmentScheduleResponse = await client.instalmentSchedules.cancel('IS123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });
});
