// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

import * as nock from 'nock';
import { GoCardlessClient } from '../client';
import { Environments } from '../constants';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as Types from '../types/Types';

describe('Mandates Code Samples', () => {
  const token = 'SECRET_TOKEN';
  let client: GoCardlessClient;

  beforeAll(() => {
    nock.disableNetConnect();
  });

  beforeEach(() => {
    client = new GoCardlessClient(token, Environments.Live, {});
  });

  afterEach(() => {
    nock.cleanAll();
  });

  test('create code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/mandates';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { mandates: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const mandate = await client.mandates.create({
        scheme: 'bacs',
        metadata: {
          contract: 'ABCD1234',
        },
        links: {
          customer_bank_account: 'BA123',
          creditor: 'CR123',
        },
      });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('list code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/mandates';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { mandates: [{}], meta: { cursors: {}, limit: 50 } };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const mandates = await client.mandates.list();

      // List all mandates associated with a given customer.
      const customerMandates = await client.mandates.list({ customer: 'CU123' });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('get code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/mandates/:identity';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { mandates: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const mandate = await client.mandates.find('MD123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('update code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/mandates/:identity';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { mandates: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').put(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const mandate = await client.mandates.update('MD123', {
        metadata: { key: 'value' },
      });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('cancel code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/mandates/:identity/actions/cancel';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { mandates: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const mandateResponse = await client.mandates.cancel('MD123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('reinstate code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/mandates/:identity/actions/reinstate';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { mandates: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const mandateResponse = await client.mandates.reinstate('MD123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });
});
