// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

import * as nock from 'nock';
import { GoCardlessClient } from '../client';
import { Environments } from '../constants';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as Types from '../types/Types';

describe('Subscriptions Code Samples', () => {
  const token = 'SECRET_TOKEN';
  let client: GoCardlessClient;

  beforeAll(() => {
    nock.disableNetConnect();
  });

  beforeEach(() => {
    client = new GoCardlessClient(token, Environments.Live, {});
  });

  afterEach(() => {
    nock.cleanAll();
  });

  test('create code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/subscriptions';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { subscriptions: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const subscription = await client.subscriptions.create({
        amount: '2500',
        currency: 'GBP',
        name: 'Monthly Magazine',
        interval_unit: 'monthly',
        day_of_month: '1',
        metadata: {
          order_no: 'ABCD1234',
        },
        links: {
          mandate: 'MA123',
        },
      });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('list code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/subscriptions';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { subscriptions: [{}], meta: { cursors: {}, limit: 50 } };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const subscriptions = await client.subscriptions.list();

      // List all subscriptions associated with a given customer.
      const customerSubscriptions = await client.subscriptions.list({ customer: 'CU123' });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('get code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/subscriptions/:identity';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { subscriptions: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const subscription = await client.subscriptions.find('SB123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('update code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/subscriptions/:identity';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { subscriptions: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').put(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const subscription = await client.subscriptions.update('SB123', {
        amount: '42',
        name: 'New Name',
      });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('pause code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/subscriptions/:identity/actions/pause';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { subscriptions: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const subscriptionResponse = await client.subscriptions.pause('SB123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('resume code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/subscriptions/:identity/actions/resume';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { subscriptions: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const subscriptionResponse = await client.subscriptions.resume('SB123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('cancel code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/subscriptions/:identity/actions/cancel';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { subscriptions: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const subscriptions = await client.subscriptions.cancel('SB123');
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });
});
