// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

import * as nock from 'nock';
import { GoCardlessClient } from '../client';
import { Environments } from '../constants';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as Types from '../types/Types';

describe('VerificationDetails Code Samples', () => {
  const token = 'SECRET_TOKEN';
  let client: GoCardlessClient;

  beforeAll(() => {
    nock.disableNetConnect();
  });

  beforeEach(() => {
    client = new GoCardlessClient(token, Environments.Live, {});
  });

  afterEach(() => {
    nock.cleanAll();
  });

  test('create code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/verification_details';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { verification_details: {} };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').post(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const verificationDetail = await client.verificationDetails.create({
        name: 'Acme',
        company_number: '03768189',
        address_line1: '12 Drury lane',
        city: 'London',
        description: 'wine and cheese seller',
        postal_code: 'B4 7NJ',
        directors: [
          {
            given_name: 'Gandalf',
            family_name: 'Grey',
            city: 'London',
            date_of_birth: '1986-02-19',
            street: 'Drury lane',
            postal_code: 'B4 7NJ',
            country_code: 'GB',
          },
        ],
        links: {
          creditor: 'CR123',
        },
      });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });

  test('list code sample executes without error', async () => {
    // Convert :param placeholders to regex wildcards for flexible matching
    const stubUrl = '/verification_details';
    const pathPattern = new RegExp('^' + stubUrl.replace(/:[\w]+/g, '[^/?]+') + '(?:\\?.*)?$');

    // Mock response - repeat multiple times to handle code samples with multiple API calls
    const responseBody = { verification_details: [{}], meta: { cursors: {}, limit: 50 } };
    for (let i = 0; i < 5; i++) {
      nock('https://api.gocardless.com').get(pathPattern).query(true).reply(200, responseBody);
    }

    // Suppress console.log from code samples
    const originalLog = console.log;
     
    console.log = () => {};

    try {
      /* eslint-disable @typescript-eslint/no-unused-vars */
      const verificationDetailList = await client.verificationDetails.list({ creditor: 'CR123' });
      /* eslint-enable @typescript-eslint/no-unused-vars */
    } finally {
      console.log = originalLog;
    }
  });
});
